import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/providers";
import "@progress/kendo-theme-default/dist/all.css";
import "./globals.css";
import style from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${style.root}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
